PLATFORM = Windows
ARCH = x86_64
TARGET_TYPE = dll

TOOLCHAIN = $(ARCH)-w64-mingw32
CC = $(TOOLCHAIN)-gcc-posix
CXX = $(TOOLCHAIN)-g++-posix
STRIP = $(TOOLCHAIN)-strip

LDFLAGS = -shared
LIBS = -static -Wl,--subsystem,windows

include Common.mk
