PLATFORM = macOS
TARGET_TYPE = dylib

SDK_MIN_VER = 11.0
ARCH_OPT = -arch $(ARCH) -mmacosx-version-min=$(SDK_MIN_VER)

CFLAGS   += $(ARCH_OPT)
CXXFLAGS += $(ARCH_OPT)
LDFLAGS  += $(ARCH_OPT) -dynamiclib

include Common.mk
